# Generated by Django 3.2.4 on 2021-06-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beemaapi', '0003_auto_20210609_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'policies'},
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
