# Generated by Django 3.2.4 on 2021-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beemaapi', '0005_auto_20210609_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
