# Generated by Django 3.2.4 on 2021-06-09 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beemaapi', '0006_alter_policy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 9, 18, 42, 28, 887777)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
