# Generated by Django 3.2.4 on 2021-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=8, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], max_length=2)),
            ],
        ),
    ]
