# Generated by Django 3.2.4 on 2021-06-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beemaapi', '0004_auto_20210609_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='policy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='beemaapi.customer'),
        ),
    ]
